src/Entity/City.php
<?php

namespace App\Entity;

use App\Model\CityRepo;
use Lib\Storage\AbstractEntity;
use Lib\Storage\Annotations\Column;
use Lib\Storage\Annotations\Table;
use Lib\Storage\Traits\AnnotationMappings;
use Lib\Storage\Traits\ColumnHydrate;
use Symfony\Component\Validator\Constraints as Assert;

#[Table('cities', CityRepo::class)]
class City extends AbstractEntity
{
    use AnnotationMappings;
    use ColumnHydrate;

    #[Column('country_code')]
    #[Assert\Length(exactly: 3, exactMessage: 'string.length')]
    public string $countryCode;

    #[Column('city_name')]
    public string $cityName;

    #[Column('longitude')]
    public float $longitude;

    #[Column('latitude')]
    public float $latitude;

    public function setId(int $id): static
    {
        $this->id = $id;
        return $this;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function setCountry(string $countryCode): static
    {
        $this->countryCode = mb_strcut($countryCode, 0, 3);
        return $this;
    }

    public function getCountry(): string
    {
        return $this->countryCode;
    }

    public function setName(string $cityName): static
    {
        $this->cityName = mb_strcut($cityName, 0, 255);
        return $this;
    }

    public function getName(): string
    {
        return $this->cityName;
    }

    public function setLong(float $longitude): static
    {
        $this->longitude = $longitude;
        return $this;
    }

    public function getLong(): float
    {
        return $this->longitude;
    }

    public function setLat(float $latitude): static
    {
        $this->latitude = $latitude;
        return $this;
    }

    public function getLat(): float
    {
        return $this->latitude;
    }
}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Model\OrderRepo;
use Lib\Storage\AbstractEntity;
use Lib\Storage\Annotations\Column;
use Lib\Storage\Annotations\Table;
use Lib\Storage\Traits\AnnotationMappings;
use Lib\Storage\Traits\ColumnHydrate;
use DateTime;

#[Table('orders', OrderRepo::class)]
class Order extends AbstractEntity
{
    use AnnotationMappings;
    use ColumnHydrate;

    #[Column('id')]
    public ?int $id;

    #[Column('buyer_id')]
    public int $buyerId;

    #[Column('seller_id')]
    public int $sellerId;

    #[Column('stand_id')]
    public int $standId;

    #[Column('date')]
    public string $date;

    #[Column('state')]
    public string $state = 'PENDING';

    public function __construct(){
        $this->date = (new DateTime('now'))->format('Y-m-d h:m:s');
    }
    public function setId(int $id): static
    {
        $this->id = $id;
        return $this;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function setBuyer(int $buyerId): static
    {
        $this->buyerId = $buyerId;
        return $this;
    }

    public function getBuyer(): int
    {
        return $this->buyerId;
    }

    public function setSeller(int $sellerId): static
    {
        $this->sellerId = $sellerId;
        return $this;
    }

    public function getSeller(): int
    {
        return $this->sellerId;
    }

    public function setStand(int $standId): static
    {
        $this->standId = $standId;
        return $this;
    }

    public function getStand(): int
    {
        return $this->standId;
    }

    public function setDate(string $date): static
    {
        $this->date = $date;
        return $this;
    }

    public function getDate(): string
    {
        return $this->date;
    }

    public function setState(string $state): static
    {
        $this->state = $state;
        return $this;
    }

    public function getState(): string
    {
        return $this->state;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Localito</title>
    <link href="https://cdn.jsdelivr.net/npm/beercss@3.4.0/dist/cdn/beer.min.css" rel="stylesheet">
    <script type="module" src="https://cdn.jsdelivr.net/npm/beercss@3.4.0/dist/cdn/beer.min.js" defer></script>
    <script type="module" src="https://cdn.jsdelivr.net/npm/material-dynamic-colors@1.0.5/dist/cdn/material-dynamic-colors.min.js" defer></script>
    <script type="module" src="/assets/main.js" defer></script>
    <link href="/assets/main.css" rel="stylesheet">
    {% block css %}{% endblock %}
    {% block js %}{% endblock %}
  </head>
  <body class="light">
  {% if login is not defined %}
    <header class="responsive fixed">
      <nav>
      {% if(rol == 'admin') %}
        <button class="circle transparent" data-ui="#menu-dialog">
          <i>menu</i>
        </button>
      {% endif %}
        <h5 class="max"><a href="/">Localito</a></h5>
      <a href="/logout" class="button transparent circle"><i>power_settings_new</i></a>
      </nav>
    </header>
    {% if(rol == 'admin') %}
    <dialog class="left" id="menu-dialog">
      <header class="fixed">
        <nav>
          <button class="transparent circle large" data-ui="#menu-dialog">
            <i>close</i>
          </button>
          <h5 class="max">Localito</h5>
        </nav>
      </header>
      {{ nav_item('home', 'home'|trans, 'home')|raw }}
      {{ nav_item('users', 'users'|trans, 'people')|raw }}
      {{ nav_item('stands', 'stands'|trans, 'storefront')|raw }}
      {{ nav_item('cities', 'cities'|trans, 'explore')|raw }}
      {{ nav_item('logout', 'logout'|trans, 'power_settings_new')|raw }}
    </dialog>
    {% endif %}
  {% endif %}
    {% block body %}{% endblock %}
  </body>
</html>

templates/city.html.twig
{% extends 'base.html.twig' %}
{% block body %}
  <main class="responsive">
    <div class="grid justify-center align-center">
      <div class="s12 flex justify-center align-center text-center my-mid2">
        <h2>{{ city.getName() }}</h2>
        <div class="row">
          <b>{{ 'input.country_code'|trans([], 'form') }}:</b>
          <div class="max">{{ city.countryCode }}</div>
        </div>
        <div class="medium-divider"></div>
        <div class="row">
          <b>{{ 'input.name'|trans([], 'form') }}:</b>
          <div class="max">{{ city.name }}</div>
        </div>
        <div class="medium-divider"></div>
        <div class="row">
          <b>{{ 'input.longitude'|trans([], 'form') }}:</b>
          <div class="max">{{ city.longitude }}</div>
        </div>
        <div class="medium-divider"></div>
        <div class="row">
          <b>{{ 'input.latitude'|trans([], 'form') }}:</b>
          <div class="max">{{ city.latitude }}</div>
        </div>
        <div class="medium-divider"></div>
        <a class="button app-back fill">{{ 'action.back'|trans }}</a>
      </div>
    </div>
  </main>
{% endblock %}

templates/city_delete.html.twig
{% extends 'base.html.twig'  %}

{% block body %}
<main class="responsive">
  <h1>{{ 'delete.city.warning'|trans({ '%username%': city.name() }) }}</h1>
  <p class="large-text">{{ 'delete.note'|trans }}</p>
  
  <nav class="my-mid">
    <a class="button fill" href="/cities">{{ 'action.back'|trans }}</a>
    <a class="button" href="?confirmation=1">{{ 'action.delete'|trans }}</a>
  </nav>
</main>
{% endblock %}

{% block style %}
<style>
  .
</style>
{% endblock %}

templates/login.html.twig
{% extends 'base.html.twig'  %}
{% form_theme form 'form/beer_theme.html.twig'  %}

{% block body %}
<main class="responsive">
  <h1>Login</h1>
  {{ form(form) }}
</main>
{% endblock %}

templates/messages.html.twig
{% extends 'base.html.twig' %}
{% block body %}
  <main class="responsive">
    <div class="grid justify-center align-center">
      <h2 class="s12">Order #{{order.id}} chat - Buyer: {{buyer.getFullName()}} </h2>
      <a class="button app-back fill">{{ 'action.back'|trans }}</a>
      <div class="grid border s12">
        {% for m in messages %}
          {% if m.userFrom == buyer.id %}
          <article class="s4">
            <h5>{{m.body}}</h5>
            <p>{{m.messageTimestamp}}</p>
          </article>
          <div class="s8"></div>
          {% else %}
          <div class="s8"></div>
            <article class="green3 s4">
            <h5>{{m.body}}</h5>
            <p>{{m.messageTimestamp}}</p>
          </article>
        {% endif %}
        {% endfor %}
      </div>
        {% include 'form/message.html.twig' %}
    </div>
  </main>
{% endblock %}

templates/order.html.twig
{% extends 'base.html.twig' %}
{% block body %}
  <main class="responsive">
    <div class="grid justify-center align-center">
      <div class="s12 flex justify-center align-center text-center my-mid2">
        <h2>Order #{{ order.id }}</h2>
        <div class="row">
          <b>{{ 'input.buyer'|trans([], 'form') }}:</b>
          <div class="max">{{ buyer }}</div>
        </div>
        <div class="medium-divider"></div>
        <div class="row">
          <b>{{ 'input.date'|trans([], 'form') }}:</b>
          <div class="max">{{ order.date }}</div>
        </div>
        <div class="medium-divider"></div>
        <div class="row">
          <b>{{ 'input.state'|trans([], 'form') }}:</b>
          <div class="max">{{ order.state }}</div>
        </div>
        <div class="medium-divider"></div>
        <a class="button app-back fill">{{ 'action.back'|trans }}</a>
        <a class="button green" href="/stand/{{order.standId}}/order/{{order.id}}/messages">Messages</a><br><br>
        {% if(order.state == 'PENDING') %}
        <a class="button blue" href="/stand/{{order.standId}}/order/{{order.id}}/update/{{'ACCEPTED'}}">Accept</a>
        <a class="button red" href="/stand/{{order.standId}}/order/{{order.id}}/update/{{'REJECTED'}}">Reject</a>
        {% endif %}
        {% if(order.state == 'ACCEPTED') %}
          <a class="button orange" href="/stand/{{order.standId}}/order/{{order.id}}/update/{{'FINISHED'}}">Finish</a>
        {% endif %}
      </div>
    </div>

    <h4 class="my-mid">Products in order</h4>
    {% if productsInOrder %}
    <table class="border" style="margin-top: 10px;">
      <thead>
        <tr>
          <th>{{ 'input.image'|trans([], 'form') }}</th>
          <th>{{ 'input.name'|trans([], 'form') }}</th>
          <th>{{ 'input.price'|trans([], 'form') }}</th>
          <th>{{ 'input.quantity'|trans([], 'form') }}</th>
          <th>{{ 'input.total'|trans([], 'form') }}</th>
        </tr>
      </thead>
      <tbody>
      {% set avatar ='restaurant.svg' %}
      {% set name = null %}
      {% set price = null %}
      {% set total = 0 %}
        {% for pio in productsInOrder %}
          {% for p in products %}
            {% if p.id == pio.productId %}
              {% set avatar = p.image == null ? 'restaurant.svg' : p.image.getPathname() %}
              {% set name = p.name == null ? null : p.name %}
              {% set price = p.price == null ? null : p.price %}
            {% endif %}
          {% endfor %}
        {% set rowClass = loop.index is even ? 'even' : 'odd' %}
        <tr class="{{ rowClass }}">
          <td><img class="circle large" src="/{{ avatar }}"></td>
          <td>{{ name }}</td>
          <td>${{ price }}</td>
          <td>{{ pio.productQuantity }}</td>
          <td>${{ pio.productQuantity * price }}</td>
          {% set total = total + (pio.productQuantity * price) %}
        </tr>
        {% endfor %}
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>${{ total }}</td>
        </tr>
      </tbody>
    </table>
    {% else %}
    <article class="border medium no-padding middle-align center-align" style="margin-top: 10px;">
      <div class="padding">
        <h5>{{ 'table.empty'|trans }}<h5>
      </div>
    </article>
    {% endif %}
  </main>
{% endblock %}

templates/orders.html.twig
{% extends  'base.html.twig' %}

{% block title %}Ordenes{% endblock %}

{% block stylesheets %}
	<style>
		.container{
			margin-top: 20px;
			max-width: 90%;
		}
	</style>
{% endblock %}

{% block body %}
	{% include 'header.html.twig' %}

	{% set orders = [
		{fecha: "XX/XX/XXXX", estado: "Pendiente"},
		{fecha: "XX/XX/XXXX", estado: "Rechazado"},
		{fecha: "XX/XX/XXXX", estado: "Aceptado"},
		{fecha: "XX/XX/XXXX", estado: "Finalizado"},
		{fecha: "XX/XX/XXXX", estado: "Pendiente"}
	] %}

	<div class="container center">
		<table class="border">
			<thead>
				<tr>
					<th>#</th>
					<th>Fecha</th>
					<th>Estado</th>
					<th></th>
				</tr>
			</thead>
		  <tbody>
		  {% for order in orders %}
			<tr>
			  <td>Orden #{{ loop.index }}</td>
			  <td>{{ order.fecha }}</td>
			  <td>{{ order.estado }}</td>
			  <td>
				<nav class="right-align">
				  <a href="/orden">
					<i>visibility</i>
				  </a>
				</nav>
			  </td>
			</tr>
		{% endfor %}
		  </tbody>
		</table>
	</div>
	
{% endblock %}

templates/product_delete.html.twig
{% extends 'base.html.twig'  %}

{% block body %}
<main class="responsive">
  <h1>{{ 'delete.product.warning'|trans({ '%username%': product.name }) }}</h1>
  <p class="large-text">{{ 'delete.note'|trans }}</p>
  
  <nav class="my-mid">
    <a class="button fill" href="/stand/{{stand.id}}">{{ 'action.back'|trans }}</a>
    <a class="button" href="?confirmation=1">{{ 'action.delete'|trans }}</a>
  </nav>
</main>
{% endblock %}

{% block style %}
<style>
  .
</style>
{% endblock %}

templates/products.html.twig
{% extends  'base.html.twig' %}

{% block title %}Productos{% endblock %}

{% block stylesheets %}
	<style>
		.container{
			margin-top: 20px;
			max-width: 90%;
		}
	</style>
{% endblock %}

{% block body %}
	{% include 'header.html.twig' %}

	{% set products = [
    	{nombre: "Cable inalambrico", precio: "10"},
    	{nombre: "Gasolina en polvo", precio: "15"},
    	{nombre: "Soplete de anillo", precio: "12"},
    	{nombre: "Disco de calibre 50", precio: "50"},
    	{nombre: "Manguera bluetooth", precio: "30"}
	] %}

	<div class="container center">
	<nav>
      <a href="/stand"><button class="border round">Volver</button></a>
    </nav>
	{% for product in products %}
		<article class="border round">
		  <div class="row">
		    <img class="circle large" src="https://www.smogon.com/forums/media/data/avatars/o/573/573216.jpg?1638992835">
		    <div class="max">
		      <h5>{{ product.nombre }}</h5>
		      <p style="font-size: 2em">${{ product.precio }}</p>
		    </div>
		  </div>
		</article>
	{% endfor %}
	</div>
	
{% endblock %}

templates/select.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<main class="responsive">
  <article class="medium no-padding" style="margin-top: 5em;">
    <div class="padding absolute center middle" style="text-align: center; display: flex; flex-direction: column; align-items: center; justify-content: center;">
      <p style="font-size: 5em;">Who are you?</p>
      <a href="loginadmin" class="button center" style="margin-bottom: 2em; width: 40em; font-size: 1.2em;"><i>shield_person</i> Admin</a>
      <a href="loginseller" class="button center" style="width: 40em; font-size: 1.2em;"><i>person</i> Seller</a>
    </div>
  </article>
</main>
{% endblock %}

templates/stand_edit.html.twig
{% extends 'base.html.twig'  %}

{% block body %}
<main class="responsive">
  <h1 class="center-align">{{ stand.id is null? 'stand.create'|trans : 'stand.edit'|trans({'%username%': stand.getName()}) }}</h1>
  {% include 'form/stand.html.twig' %}
</main>
{% endblock %}

templates/stands.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <main class="responsive mb-small">
    <h1 class="center-align">{{ 'stands'|trans }}</h1>
    {% if stands %}
      <table class="border striped responsive">
        <thead>
          <tr>
            <th class="bold">{{ 'input.name'|trans([], 'form') }}</th>
            <th class="bold">{{ 'input.tag'|trans([], 'form') }}</th>
            <th class="bold">{{ 'input.seller'|trans([], 'form') }}</th>
            <th class="bold">{{ 'input.city'|trans([], 'form') }}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for s in stands %}
            {% set rowClass = loop.index is even ? 'even' : 'odd' %}
            <tr class="flex {{ rowClass }}">
              <td>{{ s.name }}</td>
              <td>{{ s.tag }}</td>
              <td>
                {% for sl in sellers %}
                  {% for u in users %}
                    {% if s.sellerId == sl.id and sl.userId == u.id %}
                      {{ u.getFullName() }}
                    {% endif %}
                  {% endfor %}
                {% endfor %}
              </td>
              <td>
                {% for c in cities %}
                  {% if s.city == c.id %}
                    {{ c.getName() }}
                  {% endif %}
                {% endfor %}
              </td>
              <td>
                <div class="button-group">
                  <a href="/stand/{{ s.id }}" class="button info circle"><i>visibility</i></a>
                  <a href="/stand/{{ s.id }}/edit" class="button warning circle"><i>edit</i></a>
                  <a href="/stand/{{ s.id }}/delete" class="button danger circle"><i>delete</i></a>
                </div>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <article class="border medium no-padding middle-align center-align">
        <div class="padding">
          <h5>{{ 'table.empty'|trans }}<h5>
        </div>
      </article>
    {% endif %}

    <nav class="pagination">
      {% if page > 1 %}
        <a href="?page={{ page - 1}}" class="button transparent circle"><i>chevron_left</i></a>
      {% else %}
        <a disabled class="button transparent circle"><i>chevron_left</i></a>
      {% endif %}
      {{ page }}
      <a href="?page={{ page + 1 }}" class="button transparent circle"><i>chevron_right</i></a>
      <div class="my-mid">
        <a class="button success" href="/stand/new">
          <i>add</i>
          <span>{{ 'action.new'|trans }}</span>
        </a>
      </div>
    </nav>
  </main>
{% endblock %}

templates/users.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <main class="responsive mb-small">
    <h1 class="center-align">{{ 'users'|trans }}</h1>
    {% if users %}
      <table class="border striped responsive">
        <thead>
          <tr>
            <th class="bold">{{ 'input.name'|trans([], 'form') }}</th>
            <th class="bold">{{ 'input.email'|trans([], 'form') }}</th>
            <th class="bold">{{ 'input.phone'|trans([], 'form') }}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for u in users %}
            {% set rowClass = loop.index is even ? 'even' : 'odd' %}
            <tr class="flex {{ rowClass }}">
              <td>{{ u.getFullName() }}</td>
              <td>{{ u.email }}</td>
              <td>{{ u.phone }}</td>
              <td>
                <div class="button-group">
                  <a href="/user/{{ u.id }}" class="button info circle"><i>visibility</i></a>
                  <a href="/user/{{ u.id }}/edit" class="button warning circle"><i>edit</i></a>
                  <a href="/user/{{ u.id }}/delete" class="button danger circle"><i>delete</i></a>
                </div>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <article class="border medium no-padding middle-align center-align">
        <div class="padding">
          <h5>{{ 'table.empty'|trans }}<h5>
        </div>
      </article>
    {% endif %}

    <nav class="pagination">
      {% if page > 1 %}
        <a href="?page={{ page - 1}}" class="button transparent circle"><i>chevron_left</i></a>
      {% else %}
        <a disabled class="button transparent circle"><i>chevron_left</i></a>
      {% endif %}
      {{ page }}
      <a href="?page={{ page + 1 }}" class="button transparent circle"><i>chevron_right</i></a>
      <div class="my-mid">
        <a class="button success" href="/user/new">
          <i>add</i>
          <span>{{ 'action.new'|trans }}</span>
        </a>
      </div>
    </nav>
  </main>
{% endblock %}

templates/view_order.html.twig
{% extends  'base.html.twig' %}

{% block title %}Ver orden{% endblock %}

{% block stylesheets %}
	<style>
		.container{
			max-width: 90%;
		}
		p{
			font-size: 2em;
		}
	</style>
{% endblock %}

{% block body %}
	{% set order = {comprador: "Yo", stand: "La pizzeria", fecha: "XX/XX/XXXX", estado: "Acepdato"} %}
	{% set pios = [
    	{producto: "Cable inalambrico", precio: "10", cantidad: "X"},
    	{producto: "Gasolina en polvo", precio: "15", cantidad: "X"},
    	{producto: "Soplete de anillo", precio: "12", cantidad: "X"},
    	{producto: "Disco de calibre 50", precio: "50", cantidad: "X"},
    	{producto: "Manguera bluetooth", precio: "30", cantidad: "X"},
	] %}

	{% include 'header.html.twig' %}
	<div class="container center">
		<article class="no-padding">
		  <div>
		    <div>
		      <div class="padding">
		        <h2>Orden #X</h5>
		        <p>Comprador: {{ order.comprador }}</p>
		        <p>Stand: {{ order.stand }}</p>
		        <p>fecha: {{ order.fecha }}</p>
		        <nav>
		          <a href="/ordenes"><button class="border round">Volver</button></a>
		        </nav>
		        <p>Productos en la orden:</p>
		        <table class="border">
		          <thead>
		            <tr>
		              <th>Producto</th>
		              <th>Precio</th>
		              <th>Cantidad</th>
		            </tr>
		          </thead>
		          <tbody>
		          {% for pio in pios %}
		            <tr>
		              <td>{{ pio.producto }}</td>
		              <td>${{ pio.precio }}</td>
		              <td>{{ pio.cantidad }}</td>
		            </tr>
		          {% endfor %}
		          </tbody>
		        </table>
		      </div>
		    </div>
		  </div>
		</article>
	</div>
{% endblock %}